### PR TITLE
refactor(deps): Restructure into `checks/`

### PR DESCRIPTION
**Pull request by simar7**
Addresses: https://github.com/aquasecurity/trivy/issues/5609

image

### CODE REVIEW

**Comment by simar7** [comment]
TODO: This will require relocation of the following

image



image

**Comment by nikpivkin** [comment]
LGTM, but:

I think document-related commands can be deleted:
```Makefile
.PHONY: id
id:
	@go run ./cmd/id

.PHONY: docs
docs:
	go run ./cmd/avd_generator

.PHONY: docs-test
docs-test:
	go test -v ./cmd/avd_generator/...
```

**Comment by simar7** [comment]
> LGTM, but:
> 
> I think document-related commands can be deleted:
> 
> ```makefile
> .PHONY: id
> id:
> 	@go run ./cmd/id
> 
> .PHONY: docs
> docs:
> 	go run ./cmd/avd_generator
> 
> .PHONY: docs-test
> docs-test:
> 	go test -v ./cmd/avd_generator/...
> ```

Yes I've moved them here https://github.com/aquasecurity/avd-generator/pull/79 - I will remove the targets from here.

**Comment by simar7** [comment]
> TODO: This will require relocation of the following
> 
> image image

As for the tests:
1. `bundle_test.go` was brought back https://github.com/aquasecurity/trivy-policies/pull/41/commits/be424204ba52d5cb7aab59e468a9dc41d60bd272
2. `rules_test.go` was moved here https://github.com/aquasecurity/avd-generator/pull/79/commits/143b1038a90b035a5e4c562e53a62a4c0408d2ba
3. I think we can scrap `docker_test.go` as I don't see much value in keeping it.

**Review by nikpivkin — APPROVED** [review]

**Pull request merged**
